# virtualenv macros
VENV_HOME="$HOME/virtualenv/"
venvc() {
  [ -z "$1" ] || python3 -m venv ${VENV_HOME}$1
}

venv() {
  [ -z "$1" ] || source ${VENV_HOME}$1/bin/activate
}

pushover() {
  curl -s \
    --form-string "token=${PUSHOVER_TOKEN}" \
    --form-string "user=${PUSHOVER_USER}" \
    --form-string "message=$1" \
    https://api.pushover.net/1/messages.json
}

# colorful
force_color_prompt=yes
alias ls="ls --color=auto"

# always use vim
alias vi="vim"

# git shortcuts
alias gst="git status"
alias gd="git diff"
alias gdc="git diff --cached"
alias gc="git checkout"
alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)'"
alias k="kubectl"

# Map caps lock to escape
setxkbmap -option caps:escape

# Prevent Ctrl-D grief
IGNOREEOF=42

