---
- name: Ansible setup
  hosts: all
  tasks:
  - name: Add SSH Key to all remote targets
    ansible.posix.authorized_key:
      user: '{{ ansible_user }}'
      key: '{{ lookup("file", "/home/" + ansible_user_id + "/.ssh/id_rsa.pub") }}'
    when: ansible_connection != 'local'

- name: Install multimedia software
  hosts: multimedia
  gather_facts: false
  roles:
    - multimedia

- name: Install development tools
  hosts: dev
  roles:
    - dev
