---
- name: Download fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: '{{ ansible_env.HOME }}/.fzf'
    version: 'master'
    depth: 1
    single_branch: true

- name: Install fzf autocompletion
  ansible.builtin.command:
    cmd: 'bash {{ ansible_env.HOME }}/.fzf/install --all'
  tags:
    - skip_ansible_lint
